### ISSUE TITLE
Accept Header for JSON API

### ISSUE THREAD

**Issue by dpetzel** [locaweb/python-servicenow#17]
Currently the Request Session is sending an accept header of `*/*`. We have restrictions in place on our end that require the Accept header to be `application/json` when using the [tables API](http://wiki.servicenow.com/index.php?title=Table_API). If I were to submit a PR would you entertain a change something like this?

```
if self.api == 'JSON':
   self.session.headers.update({'Accept': 'application/json'})
```

**Comment by ricardojfernandes** [comment]
Done!
