### ISSUE TITLE
Need help with the usage of this API

### ISSUE THREAD

**Issue by michael132** [locaweb/python-servicenow#25]
Hello all the contributors, I contacted @PotHix for the help of querying all the data on ServiceNow including custom tables. He suggested me to create a issure here. There really isn't any documentation about this. If your time permits, would you please help understand your example code by matching it with screenshots of the corresponding data on ServiceNow? Really appreciate your help.

One of the thing I was trying to do is query all the custom tickets in a custom table. I am not even sure if I did it correctly. 

Thank you all again.
```
custom = ServiceNow.Base(conn)
custom.__table__ = "u_cmdb_ci_certificates.do"
print(json.dumps(custom.fetch_all({'PO Number': '00670460'}), indent=2))
```

![capture](https://cloud.githubusercontent.com/assets/5393905/14390535/7c4d486a-fd6c-11e5-93d8-37dd5d6dbf8b.PNG)

**Comment by PotHix** [comment]
I think you're in the right path, but you should use the column name instead of the alias "PO NUmber". You may find the real name by using the "inspect" feature of your browser and looking into the HTML.

**Comment by michael132** [comment]
thanks for the help, I think I am getting somewhere. Is it required to attach ".do" after each table name? Also, in my situation here, the Assignment Group was displayed in its sys_id rather than a human readable name. Is it normal? Sorry I am extremely new to this ServiceNow thing and thanks for the help!

**Comment by wgrcunha** [comment]
@michael132 You can use "Action Parameters"(http://wiki.servicenow.com/index.php?title=JSONv2_Web_Service#Action_Parameters) 

```
6.6 displayvalue
Get the display value of a reference field, if any are in the record. For example, the Incident record can have an assigned_to field that is a reference to a user record. Instead of sending the sys_id of the user record, the user name is sent.

The displayvalue parameter can have three values: true, false, or all.

true: All the references fields show the display value instead of sys_id.
false (default): All reference fields show sys_ids.
all: The display value and the sys_id are shown. For example, the assignedto field in the Incident record is sent back as assigned_to:1234556, dv_assigned_to:Fred Luddy.
```

For example:

```
custom.fetch_all({'key': 'value'}, params={'displayvalue': 'true'})
```

**Comment by michael132** [comment]
wow, this was extremely helpful! Thanks @wgrcunha. Can I query all the tickets assigned to a group using the group name instead of the sys_id of the group?

**Comment by wgrcunha** [comment]
@michael132 You can't, need to query group first get the sys_id and after query the table. For the next versions i can try to offer some kind of query by alias command that do this internally, but will takes some work.

**Comment by michael132** [comment]
@wgrcunha  Thanks a lot. I wasn't request for a feature that's gonna take a lot of time. I am extremely appreciated that all the contributors make this module happen :)

**Comment by PotHix** [comment]
Hope everything is ok. I'm closing this one. :)
