### ISSUE TITLE
Using the search keyword "IN" to search on multiple values

### ISSUE THREAD

**Issue by nttict-nick-b** [locaweb/python-servicenow#29]
Hi there,

Is there a way to be able to use the "IN" keyword? I'm trying to replicate the query below
"stateIN1,2,-10,-13,-11,-12,-20,-23", but couldn't see how to do it within the module.

Kind regards, Nick

https://XXXX.service-now.com/nav_to.do?uri=%2Fincident_list.do%3Fsysparm_userpref_module%3DXXXXXX%26sysparm_query%3Dactive%3Dtrue%5EstateIN1,2,-10,-13,-11,-12,-20,-23%5EEQ%26sysparm_clear_stack%3Dtrue%26sysparm_clear_stack%3Dtrue

**Comment by wgrcunha** [comment]
Hi @nttict-nick-b 

Use this release -> https://github.com/locaweb/python-servicenow/releases/tag/v2.1.1 

`
inc.fetch_all({'state': [1,2,-10,-13,-11,-12,-20,-23]})
`

**Comment by nttict-nick-b** [comment]
Thanks! I had to convert all those int to str, but it works :)

list(map(str, [1, 2, -10, -13, -11, -12, -20, -23]))
